----member 테이블 넘버 시퀀스 적용
create sequence seq_member_no;


----외래키 확인 방법
SELECT 
    CONSTRAINT_NAME
    ,CONSTRAINT_TYPE
    , TABLE_NAME
    ,R_CONSTRAINT_NAME  
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'MEMBER';


----MEMBER사업자등록번호 null 허용 변경 및 코멘트 변경
ALTER TABLE MEMBER DROP COLUMN CO_CODE;
ALTER TABLE MEMBER ADD CO_CODE NUMBER;
COMMENT ON COLUMN MEMBER.CO_CODE IS '사업자등록번호';

----컬럼순서 변경
ALTER TABLE MEMBER MODIFY PASSWORD INVISIBLE;
ALTER TABLE MEMBER MODIFY NAME INVISIBLE;
ALTER TABLE MEMBER MODIFY BIRTHDAY INVISIBLE;
ALTER TABLE MEMBER MODIFY EMAIL INVISIBLE;
ALTER TABLE MEMBER MODIFY PHONE INVISIBLE;
ALTER TABLE MEMBER MODIFY ADDRESS INVISIBLE;
ALTER TABLE MEMBER MODIFY GENDER INVISIBLE;
ALTER TABLE MEMBER MODIFY KIND INVISIBLE;
ALTER TABLE MEMBER MODIFY JOIN_DATE INVISIBLE;
ALTER TABLE MEMBER MODIFY ID INVISIBLE;
ALTER TABLE MEMBER MODIFY INTERVIEW_NO INVISIBLE;

ALTER TABLE MEMBER MODIFY PASSWORD VISIBLE;
ALTER TABLE MEMBER MODIFY NAME VISIBLE;
ALTER TABLE MEMBER MODIFY BIRTHDAY VISIBLE;
ALTER TABLE MEMBER MODIFY EMAIL VISIBLE;
ALTER TABLE MEMBER MODIFY PHONE VISIBLE;
ALTER TABLE MEMBER MODIFY ADDRESS VISIBLE;
ALTER TABLE MEMBER MODIFY GENDER VISIBLE;
ALTER TABLE MEMBER MODIFY KIND VISIBLE;
ALTER TABLE MEMBER MODIFY JOIN_DATE VISIBLE;
ALTER TABLE MEMBER MODIFY ID VISIBLE;
ALTER TABLE MEMBER MODIFY INTERVIEW_NO VISIBLE;

----DELETE_MEMBER 사업자등록번호 null 허용 변경 및 코멘트 변경
ALTER TABLE DELETE_MEMBER DROP COLUMN CO_CODE;
ALTER TABLE DELETE_MEMBER ADD CO_CODE NUMBER;
COMMENT ON COLUMN DELETE_MEMBER.CO_CODE IS '사업자등록번호';

----컬럼순서 변경
ALTER TABLE DELETE_MEMBER MODIFY PASSWORD INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY NAME INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY BIRTHDAY INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY EMAIL INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY PHONE INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY ADDRESS INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY GENDER INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY KIND INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY JOIN_DATE INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY ID INVISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY INTERVIEW_NO INVISIBLE;

ALTER TABLE DELETE_MEMBER MODIFY PASSWORD VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY NAME VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY BIRTHDAY VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY EMAIL VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY PHONE VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY ADDRESS VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY GENDER VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY KIND VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY JOIN_DATE VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY ID VISIBLE;
ALTER TABLE DELETE_MEMBER MODIFY INTERVIEW_NO VISIBLE;


----트리거 생성(MEMBER -> DLELTE_MEMBER )
create or replace TRIGGER member_before_delete
BEFORE DELETE
   ON member
   FOR EACH ROW
BEGIN
  insert into delete_member values(
    :old.member_no,
    :old.co_code,
    :old.password,
    :old.name,
    :old.birthday,
    :old.email,
    :old.phone,
    :old.address,
    :old.gender,
    :old.kind,
    :old.join_date,
    :old.id,
    :old.interviewer_no);
END;

----MEMEBER COMPANY CO_ADDRESS 컬럼 생성
ALTER TABLE MEMBER_COMPANY ADD CO_ADDRESS VARCHAR(50); 
COMMENT ON COLUMN MEMBER_COMPANY.CO_ADDRESS IS '회사주소';
ALTER TABLE MEMBER_COMPANY MODIFY CO_ADDRESS VARCHAR2(200);


----트리거 생성(MEMBER -> IR_INFO(MEMBER_NO)
create or replace TRIGGER member_no
after insert
   ON member
   FOR EACH ROW
BEGIN
 UPDATE IR_INFO SET member_no = :new.member_no
  WHERE name = :new.name
    AND phone = :new.phone
    AND email = :new.email;
END;


----MEMBER ID unique 생성
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_ID UNIQUE (ID);

---- MEMBER 테이블 INTERVIEW_NO -> INTERVIEWER_NO 컬럼명 변경
ALTER TABLE MEMBER RENAME COLUMN INTERVIEW_NO TO INTERVIEWER_NO;

---- DELETE_MEMBER 테이블 INTERVIEW_NO -> INTERVIEWER_NO 컬럼명 변경
ALTER TABLE DELETE_MEMBER RENAME COLUMN INTERVIEW_NO TO INTERVIEWER_NO;


