spring:
  datasource:
    driver-class-name: ${datasource.driverClassName}
    url: ${spring.datasource.url}  # OracleWalletConfig 클래스에서 동적으로 설정하기 때문에 이 줄은 생략 가능
    username: ${datasource.username}
    password: ${datasource.password}